global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 5m
  receiver: zabbix

receivers:
  - name: zabbix
    webhook_configs:
      - url: 'http://zal:9095/alerts'
        send_resolved: true
