apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      httpMethod: POST
      timeInterval: "15s"

  - name: Zabbix
    type: alexanderzobnin-zabbix-datasource
    uid: zabbix
    access: proxy
    url: http://zabbix-web:8080
    jsonData:
      username: Admin
      trends: true
      trendsFrom: "7d"
      trendsRange: "4d"
      cacheTTL: "1h"
    secureJsonData:
      password: zabbix
