zabbixHosts:
  - name: prometheus-lab
    itemDefaultApplication: "Prometheus Alerts"
    itemDefaultHistory: "7d"
    itemDefaultTrends: "30d"
    itemDefaultTrapperHosts: ""
    alertsDir: /etc/zal/alerts
